Upgrade sdks
EdgeApp/react-native-zcash pull request #36
Opened 2023-08-11 09:44 UTC by peachbits

2023-08-14 19:22 UTC, swansontec requested changes
The native code changes make sense. However, we should document the API changes in the readme.

2023-08-14 21:57 UTC, peachbits commented on android/gradle/wrapper/gradle-wrapper.properties
> -distributionUrl=https\://services.gradle.org/distributions/gradle-6.1.1-all.zip
No, it seems that not every gradle version gets an equal android plugin version

2023-08-14 22:46 UTC, swansontec commented on react-native-zcash.podspec
>    s.dependency "SQLite.swift", "~> 0.12"
My original branch updated to `"gRPC-Swift", "~> 1.8"`. Is this worth including?

2023-08-29 18:15 UTC, swansontec approved these changes

2023-09-04 21:55 UTC, merged